#!/usr/bin/bash

#This script processes image files in a directory called cropped.
#It creates a false color .png of the A and B data 
#and puts it in a new directory
#called shit
#The image files must be binary depth 16 endian LSB

ROWSIZE=$(expr 1680 + 0)  #Must set the ROWSIZE here
ROWSIZE=$(expr $ROWSIZE / 2) #comment if image not a cropped image

#make the directory to hold the output pngs
rm -r cropped/shit			
mkdir cropped/shit

#create a list of uniq file names to process
ls cropped -lah|sed '/^d/d'|
	awk '{print $9 }' |
	sed '/^$/d'|
	sed 's/A.dat//'| 
	sed 's/B.dat//'| 
	sed 's/Fire.dat//'|uniq>LIST.tmp

exec 6<LIST.tmp #make file descriptor for reading file names
cat LIST.tmp
i=1
while read -u 6;	#process the list of files
do
	echo "processing" $REPLY
	baz=$(wc cropped/"$REPLY"A.dat|
	awk '{print $3}')
	echo $baz
	baz=$(expr $baz / $ROWSIZE) 
	baz=$(expr $baz / 2) #baz = the number rows
	baz=$(echo "-depth 16 -endian LSB -size "$ROWSIZE"x"$baz"")
	echo "$baz"
	#if [ $i -eq 1 ]; then
	#convert "$baz" "$REPLY".png -contrast-stretch 5%x2% shit/"$REPLY"done.png;
	echo "convert "$baz" gray:cropped/"$REPLY"B.dat \
		-normalize \
		gray:tmp"$REPLY"B.dat"
	#convert -depth 16 -endian LSB -size 840x840 \
	#	gray:cropped/"$REPLY"B.dat \
	convert $baz gray:cropped/"$REPLY"B.dat \
		-normalize gray:tmp"$REPLY"B.dat
	echo "done with pre"
	convert $baz gray:cropped/"$REPLY"A.dat \
	-contrast-stretch 5%x2% \
	gray:cropped/"$REPLY"B.dat \
	-contrast-stretch 5%x2% \
	gray:tmp"$REPLY"B.dat \
	-channel red,green,blue \
	-combine\
	cropped/shit/"$REPLY"doneA.png
	rm tmp"$REPLY"B.dat;
	#fi
	i=$(expr $i + 1)

	echo "$baz";

	
	
done



exec 6<&-	


: <<'END'
echo 
echo "compiling"
gcc stretch.c
echo 
echo "running stretcher"
./a.exe rawA.dat rawB.dat rawFire.dat
echo
echo "making A image"
convert -depth 16 -endian LSB -size 1680x5683 gray:outA.dat outA.png
echo
echo "making B image"
convert -depth 16 -endian LSB -size 1680x5683 gray:outB.dat outB.png
echo "making intense B mask"
convert -depth 16 -endian LSB -size 1680x5683 gray:rawB.dat -threshold 400 -negate intenseBmask.png
convert -depth 16 -endian LSB -size 1680x5683 gray:rawB.dat -clip-mask intenseBmask.png -normalize intenseB.png
echo
echo "making false color"
convert outA.png outB.png intenseB.png -channel red,green,blue -combine false.png
#convert outB.png intenseB.png -channel green,blue -background black -combine false.png
echo "done with everything"
END
